services:
  queue:
    hostname: queue
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 15672:15672
      - 15692:15692
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user 
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  cli:
    hostname: cli
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./src:/app
    working_dir: /app
volumes:
  rabbitmq_data:
  